sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox-travis coveralls

branches:
  - develop
  - master

script: tox

after_success:
  - coveralls
